---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=0
      - TZ=America/New_York
    volumes:
      - /root/Server/.config/sonarr:/config
      - /root/Server:/server #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - homepage.group=*arrs
      - homepage.name=Sonarr
      - homepage.icon=sonarr.png
      - homepage.href=[EXTERNAL URL]
      - homepage.description=Media downloader
      - homepage.widget.type=sonarr
      - homepage.widget.url=[INTERNAL IP]
      - homepage.widget.key=[API KEY]
      
  sonarr4k:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr4k
    environment:
      - PUID=1000
      - PGID=0
      - TZ=America/New_York
    volumes:
      - /root/Server/.config/sonarr4k:/config
      - /root/Server:/server #optional
    ports:
      - 5555:5555
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - homepage.group=*arrs
      - homepage.name=Sonarr 4K
      - homepage.icon=sonarr.png
      - homepage.href=[EXTERNAL URL]
      - homepage.description=Media downloader
      - homepage.widget.type=sonarr
      - homepage.widget.url=[INTERNAL IP]
      - homepage.widget.key=[API KEY]

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /root/Server/.config/prowlarr:/config
    network_mode: "container:torguard"
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - homepage.group=*arrs
      - homepage.name=Prowlarr
      - homepage.icon=prowlarr.png
      - homepage.href=[EXTERNAL URL]
      - homepage.description=Media downloader
      - homepage.widget.type=prowlarr
      - homepage.widget.url=[INTERNAL IP]
      - homepage.widget.key=[API KEY]

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=0
      - TZ=America/New_York
    volumes:
      - /root/Server/.config/radarr:/config
      - /root/Server:/server #optional
    ports:
      - 7878:7878
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - homepage.group=*arrs
      - homepage.name=Radarr
      - homepage.icon=radarr.png
      - homepage.href=[EXTERNAL URL]
      - homepage.description=Media downloader
      - homepage.widget.type=radarr
      - homepage.widget.url=[INTERNAL IP]
      - homepage.widget.key=[API KEY]
      
  radarr4k:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr4k
    environment:
      - PUID=1000
      - PGID=0
      - TZ=America/New_York
    volumes:
      - /root/Server/.config/radarr4k:/config
      - /root/Server:/server #optional
    ports:
      - 7979:7878
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - homepage.group=*arrs
      - homepage.name=Radarr 4K
      - homepage.icon=radarr.png
      - homepage.href=[EXTERNAL URL]
      - homepage.description=Media downloader
      - homepage.widget.type=radarr
      - homepage.widget.url=[INTERNAL IP]
      - homepage.widget.key=[API KEY]
    
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=0
      - TZ=America/New_York
    volumes:
      - /root/Server/.config/bazarr:/config
      - /root/Server:/server #optional
    ports:
      - 6767:6767
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - homepage.group=*arrs
      - homepage.name=Bazarr
      - homepage.icon=bazarr.png
      - homepage.href=[EXTERNAL URL]
      - homepage.description=Media downloader
      - homepage.widget.type=bazarr
      - homepage.widget.url=[INTERNAL IP]
      - homepage.widget.key=[API KEY]
      
  whisperasr:
    image: onerahmet/openai-whisper-asr-webservice:latest
    container_name: whisperasr
    environment:
      - ASR_MODEL=small
      - ASR_ENGINE=faster_whisper
    ports:
      - 9001:9000
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    
  lidarr:
    image: blampe/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=0
      - TZ=America/New_York
    volumes:
      - /root/Server/.config/lidarr:/config
      - /root/Server:/server #optional
    ports:
      - 8686:8686
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - homepage.group=*arrs
      - homepage.name=Lidarr
      - homepage.icon=lidarr.png
      - homepage.href=[EXTERNAL URL]
      - homepage.description=Media downloader
      - homepage.widget.type=lidarr
      - homepage.widget.url=[INTERNAL IP]
      - homepage.widget.key=[API KEY]
      
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=0
      - TZ=Etc/UTC
    volumes:
      - /root/Server/.config/readarr:/config
      - /root/Server:/server #optional
    restart: unless-stopped
    ports:
      - 8787:8787
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - homepage.group=*arrs
      - homepage.name=Readarr
      - homepage.icon=readarr.png
      - homepage.href=[EXTERNAL URL]
      - homepage.description=Media downloader
      - homepage.widget.type=readarr
      - homepage.widget.url=[INTERNAL IP]
      - homepage.widget.key=[API KEY]
      
  mylar3:
    image: lscr.io/linuxserver/mylar3:nightly
    container_name: mylar3
    network_mode: "container:torguard"
    environment:
      - PUID=1000
      - PGID=0
      - TZ=America/New_York
    volumes:
      - /root/Server/.config/mylar:/config
      - /root/Server/.config/mylar/cache:/cache
      - /root/Server/mnt/drive/Library/Comics:/comics
      - /root/Server/downloads:/downloads
      - /root/Server/.config/mylar/scripts/install:/custom-cont-init.d:ro
      - /root/Server/.config/mylar/scripts:/scripts
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - autoheal=true
      - homepage.group=*arrs
      - homepage.name=Mylar
      - homepage.icon=mylar.png
      - homepage.href=[EXTERNAL URL]
      - homepage.description=Media downloader
      - homepage.widget.type=mylar
      - homepage.widget.url=[INTERNAL IP]
      - homepage.widget.key=[API KEY]
    
  soulseek:
    container_name: soulseek
    image: slskd/slskd:latest
    platform: linux/amd64
    user: 1000:0
    network_mode: "container:airvpn"
    environment:
      - TZ=America/New_York
      - SLSKD_REMOTE_CONFIGURATION=true
      - SLSKD_SHARED_DIR=/server/drive/Music
      - SLSKD_DOWNLOADS_DIR=/downloads/complete
      - SLSKD_INCOMPLETE_DIR=/downloads/downloading
      - SLSKD_FILE_PERMISSION_MODE=777
      - SLSKD_UMASK=022
      - SLSKD_SLSK_USERNAME=
      - SLSKD_SLSK_PASSWORD=
    volumes:
      - /root/Server/.config/slskd:/app
      - /root/Server/mnt:/server
      - /root/Server/downloads/complete/lidarr:/downloads
    restart: unless-stopped