---
services:
  postgresql_authentik:
    container_name: authentik-db
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 10240
        hard: 10240
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    env_file:
      - .env
    volumes:
      - /root/Server/.config/authentik/database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${AUTHENTIK_PG_PASS}
      POSTGRES_USER: ${AUTHENTIK_PG_USER}
      POSTGRES_DB: ${AUTHENTIK_PG_DB}
    networks:
      - internal_network
    labels:
      - com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLED}
      
  redis_authentik:
    container_name: authentik-redis
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis:/data
    networks:
      - internal_network
    labels:
      - com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLED}
  
  server_authentik:
    env_file:
      - .env
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-latest}
    container_name: authentik-server
    environment:
      AUTHENTIK_REDIS__HOST: redis_authentik
      AUTHENTIK_POSTGRESQL__HOST: postgresql_authentik
      AUTHENTIK_POSTGRESQL__USER: ${AUTHENTIK_PG_USER}
      AUTHENTIK_POSTGRESQL__NAME: ${AUTHENTIK_PG_DB}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${AUTHENTIK_PG_PASS}
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - /root/Server/.config/authentik/server/media:/media
      - /root/Server/.config/authentik/server/custom-templates:/templates
    ports:
      - "${AUTHENTIK_COMPOSE_PORT_HTTP:-9000}:9000"
      - "${AUTHENTIK_COMPOSE_PORT_HTTPS:-9444}:9443"
    restart: unless-stopped
    depends_on:
      postgresql_authentik:
        condition: service_healthy
      redis_authentik:
        condition: service_healthy
    labels:
      - com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLED}
      - homepage.group=Services
      - homepage.name=Authentik
      - homepage.icon=authentik.png
      - homepage.href=${AUTHENTIK_EXTERNAL_URL}
      - homepage.description=Authentication
      - homepage.widget.type=authentik
      - homepage.widget.url=${AUTHENTIK_INTERNAL_IP}
      - homepage.widget.key=${AUTHENTIK_API_KEY}

  worker_authentik:
    env_file:
      - .env
    container_name: authentik-worker
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-latest}
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: redis_authentik
      AUTHENTIK_POSTGRESQL__HOST: postgresql_authentik
      AUTHENTIK_POSTGRESQL__USER: ${AUTHENTIK_PG_USER}
      AUTHENTIK_POSTGRESQL__NAME: ${AUTHENTIK_PG_DB}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${AUTHENTIK_PG_PASS}
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/Server/.config/authentik/worker/media:/media
      - /root/Server/.config/authentik/worker/certs:/certs
      - /root/Server/.config/authentik/worker/custom-templates:/templates
    depends_on:
      postgresql_authentik:
        condition: service_healthy
      redis_authentik:
        condition: service_healthy
    labels:
      - com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLED}
      - homepage.group=Services
      - homepage.name=Authentik
      - homepage.icon=authentik.png
      - homepage.href=${AUTHENTIK_EXTERNAL_URL}
      - homepage.description=Authentication
      - homepage.widget.type=authentik
      - homepage.widget.url=${AUTHENTIK_INTERNAL_IP}
      - homepage.widget.key=${AUTHENTIK_API_KEY}

volumes:
  database:
    driver: local
  redis:
    driver: local