---
services:
  kavita:
    env_file:
      - .env
    image: jvmilazz0/kavita:nightly
    container_name: kavita
    environment:
      - TZ=${TZ}
    volumes:
      - /root/Server/.config/kavita:/kavita/config
      - /root/Server/mnt/drive/Library:/library
    ports:
      - 5001:5000
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLED}
      - homepage.group=Services
      - homepage.name=Kavita
      - homepage.icon=kavita.png
      - homepage.href=${KAVITA_EXTERNAL_URL}
      - homepage.description=Book Reader
      - homepage.widget.type=kavita
      - homepage.widget.url=${KAVITA_INTERNAL_IP}
      
  emby:
    env_file:
      - .env
    image: emby/embyserver:latest
    container_name: emby
    environment:
      - UID=${PUID}
      - GID=${PGID}
      - GIDLIST=${EMBY_GIDLIST}
      - TZ=${TZ}
    volumes:
      - /root/Server/.config/emby:/config
      - /root/Server/mnt/drive:/drive
      - /root/Server/mnt/movies/Movies:/movies
      - /root/Server/mnt/movies/Movies-4K:/movies4k
      - "/root/Server/mnt/tv/TV Shows:/tv"
      - "/root/Server/mnt/tv/TV Shows 4K:/tv4k"
      - /root/Server/mnt/drive/Music:/music
      - /root/Server/mnt/drive/Audiobooks:/audiobooks
      - /root/Server/mnt/drive/Library/:/library
    ports:
      - 8097:8096 # HTTP port
      - 8921:8920 # HTTPS port
    devices:
      - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render nodes
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLED}
      - homepage.group=Media
      - homepage.name=Emby
      - homepage.icon=emby.png
      - homepage.href=${EMBY_EXTERNAL_URL}
      - homepage.description=Media server
      - homepage.widget.type=emby
      - homepage.widget.url=${EMBY_INTERNAL_IP}
      - homepage.widget.key=${EMBY_API_KEY}
 
  audiobookshelf:
    env_file:
      - .env
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    environment:
      - UID=${PUID}
      - GID=${PGID}
    ports:
      - 13378:80
    volumes:
      - /root/Server/mnt/drive/Audiobooks:/audiobooks
      - /root/Server/mnt/drive/Library/:/library
      - /root/Server/.config/audiobookshelf/config:/config
      - /root/Server/.config/audiobookshelf/metadata:/metadata
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLED}
      - homepage.group=Services
      - homepage.name=Audiobookshelf
      - homepage.icon=audiobookshelf.png
      - homepage.href=${AUDIOBOOKSHELF_EXTERNAL_URL}
      - homepage.description=Media Status
      - homepage.widget.type=audiobookshelf
      - homepage.widget.url=${AUDIOBOOKSHELF_INTERNAL_IP}
      - homepage.widget.key=${AUDIOBOOKSHELF_API_KEY}

  plex:
    env_file:
      - .env
    container_name: plex
    image: lscr.io/linuxserver/plex
    restart: unless-stopped
    network_mode: "container:torguard"
    environment:
      - TZ=${TZ}
      - PLEX_CLAIM=
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=public
      - HOSTNAME=
      - DOCKER_MODS=linuxserver/mods:plex-audnexus
    devices:
         - /dev/dri:/dev/dri
    volumes:
      - /root/Server/.config/plex:/config
      - /root/Server/.config/plex/transcode:/transcode
      - /root/Server/mnt/movies/Movies:/movies
      - /root/Server/mnt/movies/Movies-4K:/movies4k
      - "/root/Server/mnt/tv/TV Shows:/tv"
      - "/root/Server/mnt/tv/TV Shows 4K:/tv4k"
      - /root/Server/mnt/drive/Music:/music
      - /root/Server/mnt/drive/Audiobooks:/audiobooks
      - /root/Server:/server
    labels:
      - com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLED}
      - homepage.group=Media
      - homepage.name=Plex
      - homepage.icon=plex.png
      - homepage.href=${PLEX_EXTERNAL_URL}
      - homepage.description=Media server
      - homepage.widget.type=plex
      - homepage.widget.url=${PLEX_INTERNAL_IP}
      - homepage.widget.key=${PLEX_API_KEY}
      
  ghost:
    env_file:
      - .env
    container_name: ghost
    image: ghost:alpine
    cap_add:
      - CAP_SYS_NICE
    security_opt:
      - seccomp:unconfined
    restart: always
    depends_on:
      - ghost-db
    ports:
      - 8383:2368
    environment:
      database__client: mysql
      database__connection__host: ghost-db
      database__connection__user: ${GHOST_DB_USER}
      database__connection__password: ${GHOST_DB_PASSWORD}
      database__connection__database: ${GHOST_DB_NAME}
    volumes:
      - /root/Server/.config/ghost:/var/lib/ghost/content
      - /root/Server/.config/ghost/config.production.json:/var/lib/ghost/config.production.json

  ghost-db:
    env_file:
      - .env
    container_name: ghost-db
    image: mysql:8.0
    restart: always
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: ${GHOST_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${GHOST_MYSQL_DATABASE}
      MYSQL_USER: ${GHOST_MYSQL_USER}
      MYSQL_PASSWORD: ${GHOST_MYSQL_PASSWORD}
    volumes:
      - /root/Server/.config/ghost-db:/var/lib/mysql

  jellyfin:
    env_file:
      - .env
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_PUBLISHED_SERVER_URL}
      - DOCKER_MODS=${JELLYFIN_DOCKER_MODS}
    devices:
         - /dev/dri:/dev/dri
    volumes:
      - /root/Server/.config/jellyfin:/config
      - /root/Server/mnt/drive:/drive
      - /root/Server/mnt/movies/Movies:/movies
      - /root/Server/mnt/movies/Movies-4K:/movies4k
      - "/root/Server/mnt/tv/TV Shows:/tv"
      - "/root/Server/mnt/tv/TV Shows 4K:/tv4k"
      - /root/Server/mnt/drive/Music:/music
      - /root/Server/mnt/drive/Audiobooks:/audiobooks
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    labels:
      - com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLED}
      - autoheal=true
      - homepage.group=Media
      - homepage.name=Jellyfin
      - homepage.icon=jellyfin.png
      - homepage.href=${JELLYFIN_EXTERNAL_URL}
      - homepage.description=Media server
      - homepage.widget.type=jellyfin
      - homepage.widget.url=${JELLYFIN_INTERNAL_IP}
      - homepage.widget.key=${JELLYFIN_API_KEY}
      
  romm:
    env_file:
      - .env
    image: rommapp/romm:latest
    container_name: romm
    restart: unless-stopped
    user: "0:0"
    environment:
      - DB_HOST=${ROMM_DB_HOST}
      - DB_NAME=${ROMM_DB_NAME}
      - DB_USER=${ROMM_DB_USER}
      - DB_PASSWD=${ROMM_DB_PASSWD}
      - IGDB_CLIENT_ID=${ROMM_IGDB_CLIENT_ID}
      - IGDB_CLIENT_SECRET=${ROMM_IGDB_CLIENT_SECRET}
      - ROMM_AUTH_SECRET_KEY=${ROMM_AUTH_SECRET_KEY}
      - ROMM_AUTH_USERNAME=${ROMM_AUTH_USERNAME}
      - ROMM_AUTH_PASSWORD=${ROMM_AUTH_PASSWORD}
      - ENABLE_RESCAN_ON_FILESYSTEM_CHANGE=${ROMM_ENABLE_RESCAN_ON_FS_CHANGE}
      - DISABLE_DOWNLOAD_ENDPOINT_AUTH=${ROMM_DISABLE_DOWNLOAD_ENDPOINT_AUTH}
      - DISABLE_DOWNLOAD_AUTH=${ROMM_DISABLE_DOWNLOAD_AUTH}
      - OIDC_ENABLED=${ROMM_OIDC_ENABLED}
      - OIDC_PROVIDER=${ROMM_OIDC_PROVIDER}
      - DISABLE_USERPASS_LOGIN=${ROMM_DISABLE_USERPASS_LOGIN}
      - OIDC_CLIENT_ID=${ROMM_OIDC_CLIENT_ID}
      - OIDC_CLIENT_SECRET=${ROMM_OIDC_CLIENT_SECRET}
      - OIDC_REDIRECT_URI=${ROMM_OIDC_REDIRECT_URI}
      - OIDC_SERVER_APPLICATION_URL=${ROMM_OIDC_SERVER_APPLICATION_URL}
    volumes:
      - '/root/Server/.config/romm/resources:/romm/resources' # Resources fetched from IGDB (covers, screenshots, etc.)
      - '/root/Server/mnt/drive/ROMs/Nintendo Entertainment System:/romm/library/nes/roms'
      - '/root/Server/mnt/drive/ROMs/Super Nintendo Entertainment System:/romm/library/snes/roms'
      - '/root/Server/mnt/drive/ROMs/Nintendo Gamecube:/romm/library/ngc/roms'
      - '/root/Server/mnt/drive/ROMs/Nintendo 64:/romm/library/n64/roms'
      - '/root/Server/mnt/drive/ROMs/Nintendo Wii:/romm/library/wii/roms'
      - '/root/Server/mnt/drive/ROMs/Nintendo Wii U:/romm/library/wiiu/roms'
      - '/root/Server/mnt/drive/ROMs/Nintendo Switch:/romm/library/switch'
      - '/root/Server/mnt/drive/ROMs/Nintendo Gameboy:/romm/library/gb/roms'
      - '/root/Server/mnt/drive/ROMs/Nintendo Gameboy Color:/romm/library/gbc/roms'
      - '/root/Server/mnt/drive/ROMs/Nintendo Gameboy Advance:/romm/library/gba/roms'
      - '/root/Server/mnt/drive/ROMs/Nintendo DS:/romm/library/nds/roms'
      - '/root/Server/mnt/drive/ROMs/Nintendo 3DS:/romm/library/3ds'
      - '/root/Server/mnt/drive/ROMs/Nintendo Virtual Boy:/romm/library/virtualboy/roms'
      - '/root/Server/mnt/drive/ROMs/Sega Genesis:/romm/library/genesis-slash-megadrive/roms'
      - '/root/Server/mnt/drive/ROMs/Sega 32X:/romm/library/sega32/roms'
      - '/root/Server/mnt/drive/ROMs/Sega CD:/romm/library/segacd/roms'
      - '/root/Server/mnt/drive/ROMs/Sega Dreamcast:/romm/library/dc/roms'
      - '/root/Server/mnt/drive/ROMs/Sega Saturn:/romm/library/saturn/roms'
      - '/root/Server/mnt/drive/ROMs/Sony PlayStation:/romm/library/ps'
      - '/root/Server/mnt/drive/ROMs/Sony PlayStation 2:/romm/library/ps2'
      - '/root/Server/mnt/drive/ROMs/Sony PlayStation 3:/romm/library/ps3/roms'
      - '/root/Server/mnt/drive/ROMs/Sony PlayStation Portable:/romm/library/psp/roms'
      - '/root/Server/mnt/drive/ROMs/Sony PlayStation Vita:/romm/library/psvita/roms'
      - '/root/Server/mnt/drive/ROMs/Philips CD-i:/romm/library/philips-cd-i/roms'
      - /root/Server/.config/romm/redis:/redis-data
      - /root/Server/.config/romm/assets:/romm/assets # Uploaded saves, states, etc.
      - /root/Server/.config/romm/config:/romm/config # [Optional] Path where config.yml is stored
      - /root/Server/.config/romm/logs:/romm/logs # [Optional] Path where logs are stored
    ports:
      - 9090:8080
    depends_on:
      - romm-db
    labels:
      - com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLED}
      - homepage.group=Services
      - homepage.name=Romm
      - homepage.icon=romm.png
      - homepage.href=${ROMM_EXTERNAL_URL}
      - homepage.description=ROMs Collection
      - homepage.widget.type=romm
      - homepage.widget.url=${ROMM_INTERNAL_IP}
      - homepage.widget.user=${ROMM_USER}
      - homepage.widget.password=${ROMM_PASSWORD}

  romm-db:
    env_file:
      - .env
    image: mariadb:latest
    container_name: romm-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${ROMM_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${ROMM_MYSQL_DATABASE}
      - MYSQL_USER=${ROMM_MYSQL_USER}
      - MYSQL_PASSWORD=${ROMM_MYSQL_PASSWORD}
    volumes:
      - /root/Server/.config/romm/db:/var/lib/mysql
    labels:
      - com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLED}
      
  romm-comm:
    env_file:
      - .env
    image: idiosync000/romm-comm:latest
    container_name: romm-comm
    restart: unless-stopped
    environment:
      - TOKEN=${ROMM_COMM_TOKEN}
      - GUILD=${ROMM_COMM_GUILD}
      - API_URL=${ROMM_COMM_API_URL}
      - USER=${ROMM_COMM_USER}
      - PASS=${ROMM_COMM_PASS}
      - DOMAIN=${ROMM_COMM_DOMAIN}
      - SYNC_RATE=${ROMM_COMM_SYNC_RATE}
      - REQUESTS_ENABLED=${ROMM_COMM_REQUESTS_ENABLED}
      - IGDB_CLIENT_ID=${ROMM_COMM_IGDB_CLIENT_ID}
      - IGDB_CLIENT_SECRET=${ROMM_COMM_IGDB_CLIENT_SECRET}
      - ENABLE_USER_MANAGER=${ROMM_COMM_ENABLE_USER_MANAGER}
      - AUTO_REGISTER_ROLE_ID=${ROMM_COMM_AUTO_REGISTER_ROLE_ID}
      - UPDATE_VOICE_NAMES=${ROMM_COMM_UPDATE_VOICE_NAMES}
      - CHANNEL_ID=${ROMM_COMM_CHANNEL_ID}
      - SHOW_API_SUCCESS=${ROMM_COMM_SHOW_API_SUCCESS}
      - CACHE_TTL=${ROMM_COMM_CACHE_TTL}
      - API_TIMEOUT=${ROMM_COMM_API_TIMEOUT}
    volumes:
      - /root/Server/.config/romm-comm:/app/data
    labels:
      - com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLED}
    
  navidrome:
    env_file:
      - .env
    container_name: navidrome
    image: deluan/navidrome:latest
    user: 1000:1000 # should be owner of volumes
    ports:
      - 4533:4533
    restart: unless-stopped
    environment:
      ND_SCANSCHEDULE: ${NAVIDROME_SCANSCHEDULE}
      ND_LOGLEVEL: ${NAVIDROME_LOGLEVEL}
      ND_SESSIONTIMEOUT: ${NAVIDROME_SESSIONTIMEOUT}
      ND_DEFAULTTHEME: ${NAVIDROME_DEFAULTTHEME}
      ND_ENABLECOVERANIMATION: ${NAVIDROME_ENABLECOVERANIMATION}
      ND_REVERSEPROXYUSERHEADER: ${NAVIDROME_REVERSEPROXYUSERHEADER}
      ND_REVERSEPROXYWHITELIST: ${NAVIDROME_REVERSEPROXYWHITELIST}
    volumes:
      - "/root/Server/.config/navidrome:/data"
      - "/root/Server/mnt/drive/Music:/music:ro"
    labels:
      - com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLED}
      - homepage.group=Services
      - homepage.name=Navidrome
      - homepage.icon=navidrome.png
      - homepage.href=${NAVIDROME_EXTERNAL_URL}
      - homepage.description=Music Player
      - homepage.widget.type=navidrome
      - homepage.widget.url=${NAVIDROME_INTERNAL_IP}
      - homepage.widget.user=${NAVIDROME_USER}
      - homepage.widget.token=${NAVIDROME_TOKEN}
      - homepage.widget.salt=${NAVIDROME_SALT}

  portainer:
    env_file:
      - .env
    container_name: portainer
    image: portainer/portainer-ce:lts
    command: -H unix:///var/run/docker.sock
    restart: always
    environment:
      - VIRTUAL_HOST=${PORTAINER_VIRTUAL_HOST}
      - VIRTUAL_PORT=${PORTAINER_VIRTUAL_PORT}
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      
  podfetch:
    env_file:
      - .env
    container_name: podfetch
    image: samuel19982/podfetch:latest
    ports:
      - 9292:8000
    volumes:
      - /root/Server/mnt/drive/Podcasts:/app/podcasts
      - /root/Server/.config/podfetch:/app/db
    environment:
      - POLLING_INTERVAL=${PODFETCH_POLLING_INTERVAL}
      - SERVER_URL=${PODFETCH_SERVER_URL}
      - DATABASE_URL=${PODFETCH_DATABASE_URL}

  homebox:
    env_file:
      - .env
    image: ghcr.io/sysadminsmedia/homebox:latest
    container_name: homebox
    restart: always
    environment:
      - HBOX_LOG_LEVEL=${HOMEBOX_LOG_LEVEL}
      - HBOX_LOG_FORMAT=${HOMEBOX_LOG_FORMAT}
      - HBOX_WEB_MAX_FILE_UPLOAD=${HOMEBOX_WEB_MAX_FILE_UPLOAD}
      - HBOX_OPTIONS_ALLOW_ANALYTICS=${HOMEBOX_OPTIONS_ALLOW_ANALYTICS}
      - HBOX_OPTIONS_ALLOW_REGISTRATION=${HOMEBOX_OPTIONS_ALLOW_REGISTRATION}
    volumes:
      - /root/Server/mnt/drive/homebox:/data/
    ports:
      - 7745:7745

volumes:
  portainer_data: